theme: jekyll-theme-cayman

title: "Solidity Master Cheatsheet"
description: "A comprehensive cheatsheet for Solidity developers."
author: "Aiden Park"

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap

seo:
    twitter:
        site: "@adn_park"
    open_graph:
        type: "website"
        locale: "en_US"
        url: "https://adnpark.github.io/solidity-cheatsheet/"
        site_name: "Solidity Master Cheatsheet"

extra_head: |
    <!-- Google Site Verification -->
    <meta
        name="google-site-verification"
        content="VWFnA6P8Hr64mmLdsN34F0l9tG23nQEs6vtyaedJJk0"
    />
